# Generated by Django 2.0.5 on 2018-12-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='line_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='line_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='parent',
            field=models.CharField(default='', max_length=64),
        ),
    ]
