# Generated by Django 2.0.5 on 2018-12-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monopolyapp', '0002_auto_20181214_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='player',
            name='line_id',
            field=models.CharField(default='', max_length=64, primary_key=True, serialize=False),
        ),
    ]
